# Entono de pruebas(Usamoos H2 en memoria)

spring.datasource.url=jdbc:h2:mem:ecommerce_tech
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=123

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.h2.console.enabled=true
